#!/bin/bash
os9 copy -r ~/projects/livingworlds/fnx-os9/livingworlds ~/projects/nitros9/level2/f256/NOS9_6809_L2_v030300_f256jr_sd.dsk,CMDS/livingworlds
os9 attr ~/projects/nitros9/level2/f256/NOS9_6809_L2_v030300_f256jr_sd.dsk,CMDS/livingworlds -epe
os9 copy -r ~/projects/livingworlds/fnx-os9/pixmap8raw ~/projects/nitros9/level2/f256/NOS9_6809_L2_v030300_f256jr_sd.dsk,CMDS/pixmap8raw
os9 copy -r ~/projects/livingworlds/fnx-os9/colors8 ~/projects/nitros9/level2/f256/NOS9_6809_L2_v030300_f256jr_sd.dsk,CMDS/colors8
os9 attr ~/projects/nitros9/level2/f256/NOS9_6809_L2_v030300_f256jr_sd.dsk,CMDS/colors8 -epe
